export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const HEALTH_KIT_INITIALIZE_SUCCESS = 'HEALTH_KIT_INITIALIZE_SUCCESS';
export const HEART_RATE_SAMPLES_GET_SUCCESS = 'HEART_RATE_SAMPLES_GET_SUCCESS';
export const HEART_RATE_SAMPLES_UPLOAD_SUCCESS =
  'HEART_RATE_SAMPLES_UPLOAD_SUCCESS';
export const HEALTH_KIT_ERROR = 'HEALTH_KIT_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const LOADER_STOP = 'LOADER_STOP';
export const LOADER_START = 'LOADER_START';
export const HEART_RATE_SAMPLES_RESET = 'HEART_RATE_SAMPLES_RESET';
